version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - npm ci
  pre_build:
    on-failure: ABORT
    commands:
      - npm run test
      - npm run pact:publish
      - npm run pact:can-i-deploy
  build:
    on-failure: ABORT
    commands:
      - ./deploy.sh
      - npm run pact:record-deployment
