version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - npm ci
  pre_build:
    on-failure: ABORT
    commands:
      - npm run test
      - npm run test:publish
  build:
    on-failure: ABORT
    commands:
      - aws amplify start-job --app-id d2ii8dlssorfy8 --branch-name main --job-type RELEASE
